export const ActionType = {
    SET_PRODUCTS : "SET_PRODUCTS",
    SELECTED_PRODUCT:"SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT:"REMOVE_SELECTED_PRODUCT",
    ADD_TODO:"ADD_TODO",
    REMOVE_TODO:"REMOVE_TODO",
    UPDATE_TODO:"UPDATE_TODO"
}